on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n customerportalmvc3 -g customerportalmvc39e16-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n customerportalmvc3 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n customerportalmvc3 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n customerportalmvc3 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: customerportalmvc3.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t customerportalmvc3.azurecr.io/customerportalmvc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push customerportalmvc3.azurecr.io/customerportalmvc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_customerportalmvc_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep customerportalmvcbf88 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace customerportalmvcbf88`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: customerportalmvcbf88
        container-registry-url: customerportalmvc3.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: customerportdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: customerportalmvcbf88
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          customerportalmvc3.azurecr.io/customerportalmvc:${{ github.sha }}
        imagepullsecrets: |
          customerportdockerauth   
